Target Android 13 in the Uno Project
nventive/AsyncWebView pull request #27
Opened 2023-03-23 18:45 UTC by Emmanuel-Low-Kien

GitHub Issue: #

## Proposed Changes

 - [ ] Bug fix
 - [ ] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build or CI related changes
 - [ ] Documentation content changes
 - [x] Other, please describe: Chore

## What is the current behavior?

- The project targets android 11 and 12
- Uno library supports android sdk 11 and 12

## What is the new behavior?

- The project targets android 12 and 13
- Uno library supports android sdk 12 and 13

## Impact on version

- [ ] **Major** (Public API was modified.)
  - Public constructs (class, struct, delegate, enum, etc.) were removed or renamed.
  - Public members were removed or renamed.
  - Public method signatures were changed or renamed.
- [ ] **Minor** (Public API was extended.)
  - Public constructs, members, or overloads were added.
- [x] **Patch** (Public API was unchanged.)
  - A bug in behavior was fixed.
  - Documentation was changed.
- [ ] **None** (The library is unchanged.)
  - Only code under the `build` folder was changed.
  - Only code under the `.github` folder was changed.

## Checklist

Please check that your PR fulfills the following requirements:

- [ ] Documentation has been added/updated.
- [ ] Automated Unit / Integration tests for the changes have been added/updated.
- [ ] Updated [BREAKING_CHANGES.md](../BREAKING_CHANGES.md) (if you introduced a breaking change).
- [ ] Your conventional commits are aligned with the **Impact on version** section.

## Other information

2023-05-10 19:49 UTC, CBrunet2212 approved these changes

2023-05-10 19:58 UTC, jeanplevesque approved these changes

2023-05-10 19:59 UTC, jeanplevesque requested changes

2023-05-10 19:59 UTC, jeanplevesque commented on src/AsyncWebView.Uno/AsyncWebView.Uno.csproj
> -		<TargetFrameworks Condition="'!$([MSBuild]::IsOsPlatform(OSX))'">netstandard2.0;xamarinios10;monoandroid11.0;monoandroid12.0;uap10.0.19041</TargetFrameworks>
Removing support for Android 11 is a breaking change and should be documented as such.

2023-11-28 14:44 UTC, carlh98 commented
PR not needed since we're moving away from Xamain

2023-11-28 14:44 UTC, closed without merging