feat: add support for WinUI and impl WebView2 for WinUI package
nventive/AsyncWebView pull request #29
Opened 2023-05-08 22:06 UTC by GabrielChouinardLetourneau

GitHub Issue: #

## Proposed Changes

## What is the current behavior?

No support for WinUI and using the WebView from Windows.UI.Xaml.

## What is the new behavior?

Add support for WinUI and implement WebView2 for that new package

## Checklist

Please check if your PR fulfills the following requirements:

- [ ] Documentation has been added/updated
- [ ] Automated Unit / Integration tests for the changes have been added/updated
- [ ] Contains **NO** breaking changes
- [ ] Updated the Changelog
- [ ] Associated with an issue

## Other information

2023-05-08 22:14 UTC, carlh98 commented on src/AsyncWebView.Uno.WinUI/AsyncWebView/AsyncWebView.WinUI.cs
> +namespace AsyncWebView
namespace AsyncWebView;

2023-05-09 12:45 UTC, carlh98 commented on src/AsyncWebView.Uno.WinUI/AsyncWebView/AsyncWebView.WinUI.cs
> +	/// Implementation of <see cref="AsyncWebView"/> for Windows
dot at the end

2023-05-09 12:48 UTC, carlh98 commented on src/AsyncWebView.Uno/AsyncWebView.Uno.csproj
> -    <PackageReference Include="Uno.UI" Version="4.9.0-dev.811" />
Why do we increase the version of Uno.UI?

2023-05-09 12:48 UTC, carlh98 commented on src/AsyncWebView.Uno/AsyncWebView.Uno.csproj
> -    <PackageReference Include="Uno.UI" Version="4.9.0-dev.811" />
It should stay at the main branch version

2023-05-09 12:49 UTC, carlh98 commented on src/AsyncWebView.Uno.WinUI/AsyncWebView/AsyncWebView.cs
> +using System.Net.Http;
reorder the usings

2023-05-09 12:49 UTC, carlh98 commented on src/AsyncWebView.Uno.WinUI/AsyncWebView/AsyncWebView.cs
> +namespace AsyncWebView
namespace AsyncWebView;

2023-05-09 15:06 UTC, GabrielChouinardLetourneau commented
I will push changes related to the pipeline

2023-05-09 15:55 UTC, Guidemarcus requested changes

2023-05-09 15:58 UTC, GabrielChouinardLetourneau commented on src/AsyncWebView.Uno/AsyncWebView.Uno.csproj
> +    <PackageReference Include="Uno.UI" Version="4.9.0-dev.969" />
This is update in the feature branch in the last [PR](https://github.com/nventive/AsyncWebView/pull/28), but I reverted the change like CH mentioned

2023-05-09 16:02 UTC, GabrielChouinardLetourneau commented on src/AsyncWebView.Uno.WinUI/AsyncWebView.Uno.WinUI.csproj
> +        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.755" />
Yes, we need them for the windows net 6 target

2023-05-09 16:03 UTC, GabrielChouinardLetourneau commented on src/Shared/Helpers/CompletionCommandArgs.cs
> +﻿#if WINDOWS_UWP || __ANDROID__ || __IOS__ || __WASM__ || WINDOWS10_0_18362_0_OR_GREATER
I will define a constant WINDOWS_WINUI to make it more readable. Nventive.View had the same strategy

2023-05-09 16:05 UTC, GabrielChouinardLetourneau commented on src/AsyncWebView.Uno.WinUI/AsyncWebView.Uno.WinUI.csproj
> +	</PropertyGroup>
We need that constant for netstandard and 1 condition regarding the `StringExtensions`, unless we remove the netstandard target, I would keep it like other WinUI packages we created

2023-05-09 16:24 UTC, Guidemarcus approved these changes

2023-05-09 17:19 UTC, carlh98 commented on src/AsyncWebView.Uno/AsyncWebView.Uno.csproj
> +		<PackageReference Include="Uno.SourceGenerationTasks" Version="4.2.0" />
this is needed?

2023-05-09 18:03 UTC, merged